### PR TITLE
feat: add healthcheck for crane-scheduler-controller

### PR DESCRIPTION
**Pull request by zwForrest**
## Description
Add healthcheck for crane-scheduler-controller

### CODE REVIEW

**Comment by zwForrest** [comment]
## Related PR
https://github.com/gocrane/crane-scheduler/pull/13

**Review by qmhu — COMMENTED** [review]
have you tested in helm lint?

**Comment by zwForrest** [comment]
> have you tested in helm lint?

An error occurred in an already existing file(scheduler-deployment.yaml). I will update this file.

**Comment by xieydd** [comment]
the crane-shceuler deployment error is already fixed in this commit, https://github.com/gocrane/helm-charts/commit/c67bf852fc8d3f64c1b2d5bb42fd8ee09276622a , you can cc, if you want to add health check for controller, you can update your commit, thanks for your contribution.

**Comment by zwForrest** [comment]
@xieydd commit has been updated.

**Review by xieydd — APPROVED** [review]
/lgtm

**Comment by xieydd** [comment]
@qmhu we can merge this pr. @zwForrest Thanks for your contribution.

**Pull request merged**
