### PR TITLE
pref: optimized nginx configuration

### PR DESCRIPTION
**Pull request by lbbniu**

### CODE REVIEW

**Comment by qmhu** [comment]
Is this related to the issue that add remote cluster failed.

**Comment by lbbniu** [comment]
> Is this related to the issue that add remote cluster failed.

yes

**Comment by lbbniu** [comment]
> Is this related to the issue that add remote cluster failed.

sync https://github.com/gocrane/crane/pull/551

**Comment by qmhu** [comment]
Close this issue because of https://github.com/gocrane/crane/pull/678

**Pull request closed without merging**
